# Generated by Django 6.0.4 on 2026-05-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_solicitud',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
    ]
