# Generated by Django 6.0.4 on 2026-05-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_rename_fecha_solicitud_prestamo_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
