# Generated by Django 6.0.4 on 2026-05-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_prestamo_activo_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha',
            new_name='fecha_solicitud',
        ),
    ]
