# Generated by Django 6.0.4 on 2026-05-11 01:40

import libros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_rename_fecha_prestamo_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_limite',
            field=models.DateTimeField(default=libros.models.fecha_limite_default),
        ),
    ]
